### ISSUE TITLE
Heatmap doesn't appear in Chrome

### ISSUE THREAD

**Issue by HarryCutts** [soton-ecs-2014-gdp-12/authoring-tool#27]
May be intermittent.

**Comment by chewett** [comment]
I wasnt aware that there was a heatmap in the authoring tool? I thought we had the lines (whatever they are called) for the questions and these dont seem to be appearing.

More comment needed.

**Comment by HarryCutts** [comment]
Hrng, you're right, it doesn't. I don't remember filing this issue, but I may well have done it on the wrong repository...
